services:
  ollama:
    image: ollama/ollama
    container_name: tempollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    command: serve
  
  dnd-game:
    build: .
    env_file: ".env"
    ports:
      - 8501:8501
    develop:
      watch:
        - action: sync
          path: ./src 
          target: /app/src
        
        - action: rebuild
          path: requirements.txt


volumes:
  ollama:
    external: true