FROM python:3.11-slim

WORKDIR /app/backend

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install -e .

CMD ["streamlit", "run", "main.py"]

EXPOSE 8501